package br.com.ontoiot;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class OntoIotUtil {

    public static final String DBRESOURCES = "src/main/resources/";
    public static final String NS = "http://www.semanticweb.org/flavio/ontologies/2020/8/untitled-ontology-4#";
    public static final String RDFSNS = "http://www.w3.org/2000/01/rdf-schema#";
    public static final String INPUTFOLDER = DBRESOURCES + "input/";
    public static final String OUTPUTFOLDER = DBRESOURCES + "output/";
    public static final String OWLISD = DBRESOURCES + "/ontologies/ioTSubdomains.owl";
    public static final String OWLSC = DBRESOURCES + "/ontologies/sensorCategory.owl";
    public static final String PSUBCLASSOF = OntoIotUtil.RDFSNS + "subClassOf";
    public static final ArrayList<ArrayList<String>> SUBDOMAINSANDANONIMIZATION = new ArrayList<>() {{
        add(new ArrayList<>(List.of("Logistic", "IndustrialProcesses", "SmartHome")));
        add(new ArrayList<>(List.of("Agriculture", "IndependentLiving", "HealthCare")));
        add(new ArrayList<>(List.of("Undefined", "SmartGrid", "SecurityPublic")));
        add(new ArrayList<>(List.of("UrbanMobility", "SmartCampus")));
    }};


    public static final HashMap<String, ArrayList<String>> SUBDOMAINS = new HashMap<>() {{
        put("Agriculture", new ArrayList<>(List.of("DataAirPressure", "DataAnimalHealth", "DataEnvironmentalBrightness", "DataEnvironmentalTemperature", "DataHumiditySoil", "DataIrrigation", "DataMonitoringPlantations", "DataQualitySoil", "DataRelativeHumidityAir")));
        put("HealthCare", new ArrayList<>(List.of("DataPersonalAssistants", "DataPhysicalExercises", "DataPhysiologicalSigns", "DataSleepMonitoring")));
        put("IndependentLiving", new ArrayList<>(List.of("DataConditionElderly", "DataCorporateAreaNetworks", "DataIdentificationMedicalInstrumentation", "DataMaterialIdentification", "DataSmartBeds", "DataVitalFunctionsMonitoring")));
        put("IndustrialProcesses", new ArrayList<>(List.of("DataDangerousGoods", "DataDistanceOtherVehicles", "DataDrivingTime", "DataIndustrialEquipmentOperation", "DataIndustrialManagement", "DataIndustrialProduction", "DataPressureTiresVehicle", "DataSpeedVehicles", "DataVehicleDriverPresence", "DataVehicleEngine", "DataVehicleFuelConsumption", "DataVehicleLocation", "DataVehicleStops")));
        put("Logistic", new ArrayList<>(List.of("DataDoor", "DataProductIdentification", "DataProductsLocation", "DataQualityProduct", "DataStockLevel", "DataVehicleFuelConsumption", "DataVehicleLocation", "DataVehicleSpeedControl")));
        put("SecurityPublic", new ArrayList<>(List.of("DataDevicesDetectShots", "DataDisasterAlerts", "DataFacialRecognitionSmartCameras", "DataPresence", "DataRealTimeLocation", "DataSecurityAlarms", "DataSecurityCameras", "DataSmartSensing")));
        put("SmartCampus", new ArrayList<>(List.of("DataBiometric", "DataCampusEnergyControl", "DataEnvironmentalMonitoringSystem", "DataFacialRecognition", "DataFireDetection", "DataManagementBathrooms", "DataSmartBusTracking", "DataSmartCanteenManagement", "DataSmartLibrary", "DataSmartLighting", "DataSmartParking", "DataSmartSecurity", "DataSmartVisitorMonitoring", "DataSmartWasteManagement")));
        put("SmartGrid", new ArrayList<>(List.of("DataConnectedDevicesEnergy", "DataEnergyConsumption", "DataEnergyGeneration", "DataEnergyStorage", "DataEnergyTransmission", "DataPowerEnergy", "DataTimeUseDevices")));
        put("SmartHome", new ArrayList<>(List.of("DataAccessManagement", "DataAutomationLighting", "DataBroadBandGateways", "DataCellPhoneUsage", "DataElectronicLocks", "DataHouseLocation", "DataHouseTemperature", "DataIntrusionDetection", "DataIrrigationAutomation", "DataPCsUsage", "DataResidentialMovement", "DataSocketsUse", "DataSoundSensors", "DataTelevisionUse", "DataThermostatsUse", "DataUseAutomatedBlinds", "DataUseElectricAppliances", "DataUseLaptops", "DataUseLights", "DataUserHabits", "DataVideoSurveillance")));
        put("Undefined", new ArrayList<>(List.of("DataUndefined")));
        put("UrbanMobility", new ArrayList<>(List.of("DataCommunicationVehicleInfrastructure", "DataCommunicationVehicleVehicle", "DataCrowdsPeople", "DataHighFalantes", "DataMonitoringCamera", "DataParkingAvailableSpaces", "DataPublicTransportationSystem", "DataQueryScreens", "DataSmartTrafficSignal", "DataSpeedVehicles", "DataTrafficCongestion", "DataVehicleLocation")));
    }};

    public static final HashMap<String, ArrayList<String>> CATEGORIES = new HashMap<>() {{
        put("DataPublicTransportationSystem", new ArrayList<>(List.of("BlindSpotMonitor")));
        put("DataMonitoringPlantations", new ArrayList<>(List.of("Auxanometer", "Hyperspectral", "Leaf", "Nano")));
        put("DataSoundSensors", new ArrayList<>(List.of("Microphone")));
        put("DataRelativeHumidityAir", new ArrayList<>(List.of("Humistor", "Hydrometer", "Psychrometer")));
        put("DataElectronicLocks", new ArrayList<>(List.of("Alarm")));
        put("DataDevicesDetectShots", new ArrayList<>(List.of("Alarm", "Microphone", "SoundLocator")));
        put("DataPCsUsage", new ArrayList<>(List.of("Cmos", "ElectroOptical")));
        put("DataIndustrialProduction", new ArrayList<>(List.of("LaserSurfaceVelocimeter", "LaserSurfaceVelocimetersForMovingSurfaces", "PiezoElectricAccelerometer", "ShockDetector")));
        put("DataCorporateAreaNetworks", new ArrayList<>(List.of("Nano", "Tactile")));
        put("DataIndustrialEquipmentOperation", new ArrayList<>(List.of("Undefined")));
        put("DataAirPressure", new ArrayList<>(List.of("AirFlowMeter", "Barograph", "Barometer", "BoostGauge", "PressureGauge", "Pressure", "TimePressureGauge")));
        put("DataVehicleDriverPresence", new ArrayList<>(List.of("MotionDetector", "PassiveInfrared")));
        put("DataManagementBathrooms", new ArrayList<>(List.of("Undefined")));
        put("DataFacialRecognition", new ArrayList<>(List.of("Undefined")));
        put("DataDrivingTime", new ArrayList<>(List.of("Undefined")));
        put("DataQualitySoil", new ArrayList<>(List.of("Lysimeter", "UnattendedGround")));
        put("DataCommunicationVehicleVehicle", new ArrayList<>(List.of("AnprWhereVehiclesAreTimedOverFixedDistance")));
        put("DataIrrigation", new ArrayList<>(List.of("Nano", "WaterMeter")));
        put("DataAnimalHealth", new ArrayList<>(List.of("Biochip", "Bio", "Nano")));
        put("DataDoor", new ArrayList<>(List.of("Impact", "IncrementalEncoder", "Proximity", "Triangulation")));
        put("DataVehicleStops", new ArrayList<>(List.of("Abs", "AnprWhereVehiclesAreTimedOverFixedDistance", "Accelerometer", "AutomaticTransmissionSpeed", "PiezoElectricAccelerometer")));
        put("DataPhysiologicalSigns", new ArrayList<>(List.of("Actigraphy", "Bio", "Biochip", "Breathalyzer", "DiffusionTensorImaging", "FunctionalMagneticResonanceImaging", "Heartbeat", "MagneticResonanceImaging", "NanoTetherball", "Nano")));
        put("DataBiometric", new ArrayList<>(List.of("Undefined")));
        put("DataUseElectricAppliances", new ArrayList<>(List.of("Undefined")));
        put("DataAutomationLighting", new ArrayList<>(List.of("ElectroOptical", "IncrementalEncoder", "LedAsLight", "Light", "PassiveInfrared")));
        put("DataConnectedDevicesEnergy", new ArrayList<>(List.of("Current")));
        put("DataFireDetection", new ArrayList<>(List.of("Undefined")));
        put("DataVehicleLocation", new ArrayList<>(List.of("AnprWhereVehiclesAreTimedOverFixedDistance", "Accelerometer", "CapacitiveDisplacement", "ChargeCoupledDevice", "DisplacementReceiver", "GroundSpeedRadar", "PiezoElectricAccelerometer", "Position", "Radar", "UltraWideBandRadar")));
        put("DataUseLights", new ArrayList<>(List.of("ElectroOptical", "LedAsLight")));
        put("DataVehicleFuelConsumption", new ArrayList<>(List.of("Afr", "AirFlowMeter", "AirFuelRatioMeter", "FuelLevel", "FuelPressure", "Level", "MagneticLevelGauge", "OilLevel", "Ultrasonic")));
        put("DataResidentialMovement", new ArrayList<>(List.of("MotionDetector", "Occupancy", "PassiveInfrared")));
        put("DataRealTimeLocation", new ArrayList<>(List.of("Accelerometer", "GroundSpeedRadar", "PiezoElectricAccelerometer", "Position", "UltraWideBandRadar")));
        put("DataHumiditySoil", new ArrayList<>(List.of("CapacitanceProbe", "FrequencyDomain", "Humistor", "Hygrometer", "Lysimeter", "SoilMoisture")));
        put("DataSpeedVehicles", new ArrayList<>(List.of("AnprWhereVehiclesAreTimedOverFixedDistance", "Accelerometer", "AutomaticTransmissionSpeed", "DopplerRadar", "FreeFall", "GroundSpeedRadar", "HallEffect", "Odometer", "PiezoElectricAccelerometer", "Radar", "RadarGun", "Speedometers", "Tachometer", "VehicleSpeed", "VelocityReceiver", "WheelSpeed")));
        put("DataSmartBeds", new ArrayList<>(List.of("Cmos", "MotionDetector", "Nano", "OmnidirectionalCamera", "RangeImaging", "TimeOfFlightCamera", "Video")));
        put("DataConditionElderly", new ArrayList<>(List.of("Actigraphy", "Biochip", "Bio", "HallEffect", "Heartbeat", "Hyperspectral", "NanoTetherball", "Nano")));
        put("DataTrafficCongestion", new ArrayList<>(List.of("BlindSpotMonitor", "BrakeFluidPressure", "FreeFall")));
        put("DataEnvironmentalBrightness", new ArrayList<>(List.of("BackIlluminated", "LedAsLight")));
        put("DataSmartWasteManagement", new ArrayList<>(List.of("Undefined")));
        put("DataIdentificationMedicalInstrumentation", new ArrayList<>(List.of("Undefined")));
        put("DataPersonalAssistants", new ArrayList<>(List.of("Undefined")));
        put("DataUseLaptops", new ArrayList<>(List.of("Cmos", "ElectroOptical")));
        put("DataSmartTrafficSignal", new ArrayList<>(List.of("Undefined")));
        put("DataHouseLocation", new ArrayList<>(List.of("Position", "UltraWideBandRadar")));
        put("DataHouseTemperature", new ArrayList<>(List.of("Calorimeter", "InfraredThermometer", "Pyrometer", "QuartzThermometer", "ResistanceThermometer", "SiliconBandgapTemperature", "TemperatureGauge", "Thermocouple", "Thermometer")));
        put("DataSmartBusTracking", new ArrayList<>(List.of("Undefined")));
        put("DataDistanceOtherVehicles", new ArrayList<>(List.of("BlindSpotMonitor", "CapacitiveDisplacement", "Position", "Proximity")));
        put("DataUndefined", new ArrayList<>(List.of("Undefined")));
        put("DataVehicleEngine", new ArrayList<>(List.of("Afr", "AirFlowMeter", "AirFuelRatioMeter", "BoostGauge", "BourdonGauge", "CrankShaftPosition", "CylinderHeadTemperatureGauge", "EngineCrankcasePressure", "Knock", "Map", "MassFlow", "OilLevel", "OilPressure", "PressureGauge", "Pressure", "Tachometer", "VariableReluctance")));
        put("DataEnergyGeneration", new ArrayList<>(List.of("Current", "Galvanometer", "PhotoDiode", "StrainGauge", "TestLight", "WheatstoneBridge")));
        put("DataBroadBandGateways", new ArrayList<>(List.of("Undefined")));
        put("DataMonitoringCamera", new ArrayList<>(List.of("ActivePixel", "AngleSensitivePixel", "Image", "Microbolometer", "MotionDetector", "OmnidirectionalCamera", "RangeImaging", "StaringArray", "TimeOfFlightCamera", "Video")));
        put("DataUserHabits", new ArrayList<>(List.of("Actigraphy", "PassiveInfrared")));
        put("DataEnvironmentalTemperature", new ArrayList<>(List.of("Calorimeter", "InfraredThermometer", "Pyrometer", "QuartzThermometer", "ResistanceThermometer", "SiliconBandgapTemperature", "TemperatureGauge", "Thermocouple", "Thermometer")));
        put("DataSocketsUse", new ArrayList<>(List.of("CapacitiveSensing", "Electroscope", "TouchSwitch")));
        put("DataVideoSurveillance", new ArrayList<>(List.of("Alarm", "AnalogImageProcessing", "AngleSensitivePixel", "BackIlluminated", "Cmos", "Catadioptric", "Colorimeter", "Image", "OmnidirectionalCamera", "RangeImaging", "StaringArray", "TimeOfFlightCamera", "Video")));
        put("DataHighFalantes", new ArrayList<>(List.of("Microphone")));
        put("DataQualityProduct", new ArrayList<>(List.of("Impact", "ShockDetector")));
        put("DataSleepMonitoring", new ArrayList<>(List.of("Actigraphy", "Biochip", "Bio", "Nano")));
        put("DataEnergyTransmission", new ArrayList<>(List.of("Current", "Galvanometer", "StrainGauge", "WheatstoneBridge")));
        put("DataSmartCanteenManagement", new ArrayList<>(List.of("Undefined")));
        put("DataCampusEnergyControl", new ArrayList<>(List.of("Undefined")));
        put("DataIrrigationAutomation", new ArrayList<>(List.of("PassiveInfrared")));
        put("DataSmartLighting", new ArrayList<>(List.of("Undefined")));
        put("DataSmartVisitorMonitoring", new ArrayList<>(List.of("Undefined")));
        put("DataCellPhoneUsage", new ArrayList<>(List.of("Accelerometer", "Cmos", "Capacitance", "ElectroOptical", "Gyroscope", "Gyroscopic", "PiezoElectricAccelerometer", "PiezoElectric")));
        put("DataSmartParking", new ArrayList<>(List.of("Undefined")));
        put("DataTelevisionUse", new ArrayList<>(List.of("Undefined")));
        put("DataProductIdentification", new ArrayList<>(List.of("Undefined")));
        put("DataCommunicationVehicleInfrastructure", new ArrayList<>(List.of("Abs", "AnprWhereVehiclesAreTimedOverFixedDistance")));
        put("DataEnergyStorage", new ArrayList<>(List.of("Current", "Galvanometer", "StrainGauge", "VoltageDetector", "WheatstoneBridge")));
        put("DataSecurityCameras", new ArrayList<>(List.of("ActivePixel", "AnalogImageProcessing", "AngleSensitivePixel", "BackIlluminated", "Cmos", "Catadioptric", "Colorimeter", "Microbolometer", "OmnidirectionalCamera", "RangeImaging", "StaringArray", "TimeOfFlightCamera", "Video")));
        put("DataStockLevel", new ArrayList<>(List.of("Level")));
        put("DataThermostatsUse", new ArrayList<>(List.of("HeatFlux", "InfraredThermometer", "TemperatureGauge", "Thermometer")));
        put("DataPresence", new ArrayList<>(List.of("MotionDetector", "Occupancy", "PassiveInfrared", "Proximity")));
        put("DataPressureTiresVehicle", new ArrayList<>(List.of("AirFlowMeter", "PressureGauge", "Pressure", "TirePressure")));
        put("DataSmartLibrary", new ArrayList<>(List.of("Undefined")));
        put("DataIntrusionDetection", new ArrayList<>(List.of("Alarm", "Microphone", "MillimeterWaveScanner", "MotionDetector", "Occupancy", "PassiveInfrared")));
        put("DataProductsLocation", new ArrayList<>(List.of("Accelerometer", "GroundSpeedRadar", "IncrementalEncoder", "PiezoElectricAccelerometer", "Position", "UltraWideBandRadar")));
        put("DataDangerousGoods", new ArrayList<>(List.of("Impact", "Nano", "ShockDetector")));
        put("DataTimeUseDevices", new ArrayList<>(List.of("Undefined")));
        put("DataVehicleSpeedControl", new ArrayList<>(List.of("Abs", "AnprWhereVehiclesAreTimedOverFixedDistance", "AutomaticTransmissionSpeed", "DopplerRadar", "FreeFall", "GroundSpeedRadar", "Gyroscopic", "HallEffect", "LaserSurfaceVelocimeter", "LaserSurfaceVelocimetersForMovingSurfaces", "Odometer", "RadarGun", "Radar", "Speedometers", "Tachometer", "VehicleSpeed", "VelocityReceiver", "WheelSpeed")));
        put("DataEnvironmentalMonitoringSystem", new ArrayList<>(List.of("Undefined")));
        put("DataIntelSmartWasteManagement", new ArrayList<>(List.of("Undefined")));
        put("DataFacialRecognitionSmartCameras", new ArrayList<>(List.of("ActivePixel", "AnalogImageProcessing", "AngleSensitivePixel", "Cmos", "Catadioptric", "Colorimeter", "Image", "ImageFormat", "OmnidirectionalCamera", "RangeImaging", "StaringArray")));
        put("DataPhysicalExercises", new ArrayList<>(List.of("Accelerometer", "GroundSpeedRadar", "Heartbeat", "Nano", "PiezoElectricAccelerometer")));
        put("DataUseAutomatedBlinds", new ArrayList<>(List.of("Undefined")));
        put("DataSecurityAlarms", new ArrayList<>(List.of("Proximity", "Alarm", "GasDetector", "MillimeterWaveScanner", "PassiveInfrared")));
        put("DataIndustrialManagement", new ArrayList<>(List.of("ChargeCoupledDevice", "ShockDetector")));
        put("DataMaterialIdentification", new ArrayList<>(List.of("Undefined")));
        put("DataParkingAvailableSpaces", new ArrayList<>(List.of("BlindSpotMonitor", "Parking")));
        put("DataDisasterAlerts", new ArrayList<>(List.of("Alarm", "GasDetector", "Thermocouple")));
        put("DataCrowdsPeople", new ArrayList<>(List.of("MotionDetector", "Occupancy", "PassiveInfrared")));
        put("DataQueryScreens", new ArrayList<>(List.of("Capacitance", "PiezoElectric", "TouchSwitch")));
        put("DataSmartSensing", new ArrayList<>(List.of("Auxanometer", "Flow", "Heartbeat", "HookGaugeEvaporimeter", "Hyperspectral", "Impact", "Intelligent", "Leaf", "Nano", "PassiveInfrared", "PhotoElectric", "PushBroomScanner", "QuartzThermometer", "Snotel", "Grid", "SmartDust", "Tactile", "VisualNetwork", "WirelessNetwork")));
        put("DataSound", new ArrayList<>(List.of("Microphone")));
        put("DataAccessManagement", new ArrayList<>(List.of("Alarm", "MillimeterWaveScanner", "MotionDetector")));
        put("DataPowerEnergy", new ArrayList<>(List.of("Current", "Galvanometer", "StrainGauge", "TestLight", "VoltageDetector", "WheatstoneBridge")));
        put("DataSmartSecurity", new ArrayList<>(List.of("Undefined")));
        put("DataEnergyConsumption", new ArrayList<>(List.of("Current", "Galvanometer", "ProportionalCounter", "StrainGauge", "TestLight", "VoltageDetector", "WheatstoneBridge")));
        put("DataVitalFunctionsMonitoring", new ArrayList<>(List.of("Actigraphy", "Biochip", "Bio", "FunctionalMagneticResonanceImaging", "Heartbeat", "Nano")));
    }};
}

